using System.Diagnostics;

namespace Problems
{
    /// <summary>
    /// Source: https://projecteuler.net/problem=2
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    public static class Problem2
    {
        public static Answer Solution1(long maxValue = 4000000)
        {
            Stopwatch sw = Stopwatch.StartNew();
            long fNumber1 = 1, fNumber2  = 2, cFNumber = 0, sum =2;

            while (cFNumber < maxValue)
            {
                cFNumber = fNumber1 + fNumber2;
                if (cFNumber % 2 == 0)
                    sum += cFNumber;
                fNumber1 = fNumber2;
                fNumber2 = cFNumber;
            }
            sw.Stop();
            
            return new Answer
            {
                Result = sum,
                TimeTaken = sw.Elapsed.TotalMilliseconds
            };
        }
    }
}
